=== kadet1090/pipeCMS/system/DTD/BBcode.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    PUBLIC ID  : -//pipe-software//BBcode//EN
    SYSTEM ID  : ../system/DTD/BBcode.dtd
-->
<!ELEMENT list (BBcode*)>
    <!ELEMENT BBcode EMPTY>
    <!ATTLIST BBcode tag CDATA #REQUIRED>
    <!ATTLIST BBcode closeTag (true|false) "true">
    <!ATTLIST BBcode params CDATA #IMPLIED>
    <!ATTLIST BBcode param (true|false) "false">
    <!ATTLIST BBcode html CDATA>
    <!ATTLIST BBcode callback CDATA>

=== kadet1090/pipeCMS/cfg/BBcode.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../system/DTD/BBcode.dtd">
<list>
    <BBcode tag="b"	closeTag="true"	    html='&lt;b&gt;{text}&lt;/b&gt;'/>
    <BBcode tag="u"	closeTag="true"	    html='&lt;u&gt;{text}&lt;/u&gt;'/>
    <BBcode tag="i"	closeTag="true"	    html='&lt;i&gt;{text}&lt;/i&gt;'/>
    <BBcode tag="s"	closeTag="true"	    html='&lt;span style="text-decoration: line-through;" &gt;{text}&lt;/span&gt;'/>
    <BBcode tag="url"	closeTag="true"	    html='&lt;a href="{param}" &gt;{text}&lt;/a&gt;' param="true"/>
    <BBcode tag="url"	closeTag="true"     html='&lt;a href="{text}" &gt;{text}&lt;/a&gt;' param="false"/>
    <BBcode tag="img"	closeTag="true"	    html='&lt;img src="{text}" alt="image" /&gt;'/>
    <BBcode tag="img"	closeTag="false"    html='&lt;img src="{param}" alt="image" /&gt;' param="true"/>
    <BBcode tag="img"	closeTag="true"	    html='&lt;img src="{url}" alt="{text}" /&gt;' params="url"/>
    <BBcode tag="img"	closeTag="true"	    html='&lt;img src="{url}" alt="{text}" class="align-{align}"/&gt;'  params="url, align"/>
    <BBcode tag="img"	closeTag="false"    html='&lt;img src="{url}" class="align-{align}"/&gt;'               params="url, align"/>
    <BBcode tag="img"	closeTag="true"	    html='&lt;img src="{url}" alt="{text}" class="align-{align}" style="width: {width};"/&gt;'  params="url, align, width"/>
    <BBcode tag="img"	closeTag="false"    html='&lt;img src="{url}" class="align-{align}" style="width: {width}"/&gt;' params="url, align, width"/>
    <BBcode tag="img"	closeTag="true"	    html='&lt;img src="{param}" alt="{text}" /&gt;' param="true"/>
    <BBcode tag="font"	closeTag="true"	    html='&lt;span style="font-family: {param}"&gt;{text}&lt;/span&gt;' param="true"/>
    <BBcode tag="center" closeTag="true"    html='&lt;div class="centered"&gt;{text}&lt;/div&gt;'/>
    <BBcode tag="list"	closeTag="true"	    html='&lt;ul&gt;{text}&lt;/ul&gt;'/>
    <BBcode tag="numlist" closeTag="true"   html='&lt;ol&gt;{text}&lt;/ol&gt;'/>
    <BBcode tag="\*"	closeTag="true"	    html='&lt;li&gt;{text}&lt;/li&gt;'/>
    <BBcode tag="color"	closeTag="true"	    html='&lt;span style="color: {param};" &gt;{text}&lt;/span&gt;' param="true"/>
    <BBcode tag="size"	closeTag="true"	    html='&lt;span style="font-size: {param};" &gt;{text}&lt;/span&gt;' param="true"/>
    <BBcode tag="hr"	closeTag="false"    html='&lt;hr /&gt;'/>
    <BBcode tag="acr"	closeTag="true"	    html='&lt;abbr title="{param}"&gt;{text}&lt;/abbr&gt;' param="true"/>
    <BBcode tag="break" closeTag="false"    html='&lt;hr class="break" /&gt;' />
    <BBcode tag="more"  closeTag="false"    html='&lt;hr class="break" /&gt;' />
    <BBcode tag="code"	closeTag="true"	    html='&lt;pre class="brush: {param}"&gt;{text}&lt;/pre&gt;' param="true"/>
    <BBcode tag="bbcode" closeTag="true"    html='&lt;pre class="bbcode"&gt;{text}&lt;/pre&gt;' />
    <BBcode tag="h1"    closeTag="true"     html='&lt;h1&gt;{text}&lt;/h1&gt;' />
    <BBcode tag="h2"    closeTag="true"     html='&lt;h2&gt;{text}&lt;/h2&gt;' />
    <BBcode tag="h3"    closeTag="true"     html='&lt;h3&gt;{text}&lt;/h3&gt;' />
    <BBcode tag="h4"    closeTag="true"     html='&lt;h4&gt;{text}&lt;/h4&gt;' />
    <BBcode tag="h5"    closeTag="true"     html='&lt;h5&gt;{text}&lt;/h5&gt;' />
    <BBcode tag="h6"    closeTag="true"     html='&lt;h6&gt;{text}&lt;/h6&gt;' />
    <BBcode tag="quote"	closeTag="true"	    html='&lt;blockquote&gt;{text}&lt;div class="author"&gt;{param}&lt;/div&gt;&lt;/blockquote&gt;' param="true"/>
    <BBcode tag="quote"	closeTag="true"	    html='&lt;blockquote&gt;{text}&lt;/blockquote&gt;'/>
    <BBcode tag="align" closeTag="true"     html='&lt;p align="{param}"&gt;{text}&lt;/p&gt;' param="true"/>
    <BBcode tag="table" closeTag="true"     html='&lt;table class="data-table"&gt;{text}&lt;/table&gt;' />
    <BBcode tag="table" closeTag="true"     html='&lt;table class="data-table" style="width: {param}"&gt;{text}&lt;/table&gt;' param="true"/>
    <BBcode tag="table" closeTag="true"     html='&lt;table class="data-table align-{align}" style="width: {width}"&gt;{text}&lt;/table&gt;' params="align, width"/>
    <BBcode tag="row"   closeTag="true"     html='&lt;tr&gt;{text}&lt;/tr&gt;' />
    <BBcode tag="cell"  closeTag="true"     html='&lt;td&gt;{text}&lt;/td&gt;' />
    <BBcode tag="header" closeTag="true"    html='&lt;th&gt;{text}&lt;/th&gt;' />
    <BBcode tag="header" closeTag="true"    html='&lt;th width="{param}"&gt;{text}&lt;/th&gt;' param="true"/>
    <BBcode tag="sub"   closeTag="true"     html='&lt;sub&gt;{text}&lt;/sub&gt;' />
    <BBcode tag="sup"   closeTag="true"     html='&lt;sup&gt;{text}&lt;/sup&gt;' />
</list>
